# Generated by Xplorer, do not modify.
# This Makefile builds _single_build Debug

%:: RCS/%,v
%:: RCS/%
%:: s.%
%:: SCCS/s.%
.SUFFIXES:
.SUFFIXES: .a .o .c .cc .C .cpp .s .S .h

all:
	/bin/sh -c " cd /home/chao/xtensa/Xplorer-8.0.12-workspaces/Audio/bin/X6H3CNL_2017_8/Debug && $(MAKE) all  "

clean:
	/bin/sh -c " cd /home/chao/xtensa/Xplorer-8.0.12-workspaces/Audio/bin/X6H3CNL_2017_8/Debug && $(MAKE) clean  "
